package model.friendly;

import control.SkeletonUI;
import model.ActiveUnit;
import model.enemies.EnemyUnit;
import model.runes.Rune;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Swamp.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//

public class Swamp implements ActiveUnit, FriendlyUnit {

	private EnemyUnit enemyUnits;

	@Override
	public void tick() {
		// TODO Auto-generated method stub

	}

	@Override
	public boolean checkRune() {
		// TODO Auto-generated method stub
		SkeletonUI.enterFunction(this, "checkRune");

		String answer = SkeletonUI
				.stringQuestion(
						"What kind of rune is in the swamp? (Default, dWarf, Elf, Man, Hobbit) /Rune can be put only to swamp with default rune./",
						"D", "W", "E", "M", "H");

		boolean available = (answer.equals("D"));

		SkeletonUI.leaveFunction(available);
		return available;
	}

	@Override
	public void putRune(Rune r) {
		// TODO Auto-generated method stub
		SkeletonUI.enterFunction(this, "putRune", r);

		SkeletonUI.leaveFunction();
	}

	@Override
	public void addUnit(EnemyUnit enemyUnit) {
		// TODO Auto-generated method stub

	}

	@Override
	public void removeUnit(EnemyUnit e) {
		// TODO Auto-generated method stub
		SkeletonUI.enterFunction(this, "removeUnit", e);

		SkeletonUI.leaveFunction();
	}
}
