package model.friendly;

import java.util.ArrayList;
import java.util.List;

import model.ActiveUnit;
import model.enemies.EnemyUnit;
import model.runes.Projectile;
import model.runes.Rune;
import control.SkeletonUI;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Tower.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//

public class Tower implements ActiveUnit, FriendlyUnit {

	private List<EnemyUnit> enemyUnits = new ArrayList<EnemyUnit>();
	private Rune rune;
	private EnemyUnit lastTarget;

	@Override
	public void tick() {
		// TODO Auto-generated method stub
		SkeletonUI.enterFunction(this, "tick");

		boolean answer =  SkeletonUI.booleanQuestion("Are there any enemies to shoot?");
		if (answer) {
			
			Projectile p = new Projectile();
			SkeletonUI.addObject(p, "p", true);
			rune.modifyProjectile(p);
			
			enemyUnits.get(0).gotHit(p);			
		}
		
		SkeletonUI.leaveFunction();
	}

	@Override
	public boolean checkRune() {
		// TODO Auto-generated method stub
		SkeletonUI.enterFunction(this, "checkRune");

		String answer = SkeletonUI
				.stringQuestion(
						"What kind of rune is in the tower? (Default, dWarf, Elf, Man, Hobbit, Range, reLoad) /Rune can be put only to tower with default rune./",
						"D", "W", "E", "M", "H", "R", "L");

		boolean available = (answer.equals("D"));

		SkeletonUI.leaveFunction(available);
		return available;
	}

	@Override
	public void putRune(Rune r) {
		// TODO Auto-generated method stub
		SkeletonUI.enterFunction(this, "putRune", r);

		SkeletonUI.leaveFunction();
	}

	@Override
	public void addUnit(EnemyUnit enemyUnit) {
		// TODO Auto-generated method stub

	}

	@Override
	public void removeUnit(EnemyUnit e) {
		// TODO Auto-generated method stub
		SkeletonUI.enterFunction(this, "removeUnit", e);

		SkeletonUI.leaveFunction();
	}

	public void Skeleton_addUnit(EnemyUnit enemyUnit) {
		enemyUnits.add(enemyUnit);
	}
	
	public void Skeleton_addRune(Rune r) {
		rune = r;
	}
}
