package model.friendly;

import java.util.ArrayList;
import java.util.List;

import model.ActiveUnit;
import model.enemies.EnemyUnit;
import model.runes.Rune;
import control.SkeletonUI;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Tower.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//

public class Tower implements ActiveUnit, FriendlyUnit {

	private List<EnemyUnit> enemyUnits = new ArrayList<EnemyUnit>();

	private EnemyUnit lastTarget;

	@Override
	public void tick() {
		// TODO Auto-generated method stub
		SkeletonUI.enterFunction(this, "tick");

		SkeletonUI.leaveFunction();
	}

	@Override
	public boolean checkRune() {
		// TODO Auto-generated method stub
		SkeletonUI.enterFunction(this, "checkRune");

		SkeletonUI.leaveFunction(false);
		return false;
	}

	@Override
	public void putRune(Rune r) {
		// TODO Auto-generated method stub
		SkeletonUI.enterFunction(this, "putRune", r);

		SkeletonUI.leaveFunction();
	}

	@Override
	public void addUnit(EnemyUnit enemyUnit) {
		// TODO Auto-generated method stub

	}

	@Override
	public void removeUnit(EnemyUnit e) {
		// TODO Auto-generated method stub
		SkeletonUI.enterFunction(this, "removeUnit", e);

		SkeletonUI.leaveFunction();
	}
	
	public void Skeleton_AddUnit(EnemyUnit enemyUnit) {
		enemyUnits.add(enemyUnit);
	}
}
