//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DwarfRune.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//
package model.runes;

public class DwarfRune extends Rune {

	// public void modifyProjectile(Projectile p) {
	//
	// }
	//
	// public void modifySlime(Slime s) {
	//
	// }
}
