package model.runes;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : HobbitRune.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//

public class HobbitRune extends Rune {
	public void modifyProjectile(Projectile p) {

	}

	public void modifySlime(Slime s) {

	}
}
