package model.runes;

import model.enemies.Dwarf;
import model.enemies.Elf;
import model.enemies.Hobbit;
import model.enemies.Man;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Projectile.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//

public class Projectile {
	public void damageMe(Dwarf d) {

	}

	public void damageMe(Hobbit h) {

	}

	public void damageMe(Elf e) {

	}

	public void damageMe(Man m) {

	}

	public void setDamage() {

	}
}
