package model.runes;

import control.SkeletonUI;
import model.enemies.Dwarf;
import model.enemies.Elf;
import model.enemies.Hobbit;
import model.enemies.Man;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Projectile.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//

public class Projectile {
	public void damageMe(Dwarf d) {
		SkeletonUI.enterFunction(this, "damageMe", d);

		SkeletonUI.leaveFunction();
	}

	public void damageMe(Hobbit h) {
		SkeletonUI.enterFunction(this, "damageMe", h);

		SkeletonUI.leaveFunction();
	}

	public void damageMe(Elf e) {
		SkeletonUI.enterFunction(this, "damageMe", e);

		SkeletonUI.leaveFunction();
	}

	public void damageMe(Man m) {
		SkeletonUI.enterFunction(this, "damageMe", m);

		SkeletonUI.leaveFunction();

	}

	public void setDamage() {
		SkeletonUI.enterFunction(this, "setDamage");

		SkeletonUI.leaveFunction();

	}
}
