package model.runes;

import control.SkeletonUI;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ReloadRune.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//

public class ReloadRune extends Rune {

//	public void modifyProjectile(Projectile p) {
//
//	}
}
