package model.runes;

import control.SkeletonUI;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Rune.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//

public class Rune {

	public void modifyProjectile(Projectile p) {
		SkeletonUI.enterFunction(this, "modifyProjectile", p);
		
		
		SkeletonUI.leaveFunction();
	}

	public void modifySlime(Slime s) {
		SkeletonUI.enterFunction(this, "modifySlime", s);
		
		SkeletonUI.leaveFunction();
	}

	public int getDistance() {
		SkeletonUI.enterFunction(this, "getDistance");
		
		// I'm addicted to you, shame on me... Hollywood Newsagency!
		
		SkeletonUI.leaveFunction(0);
		return 0;
	}
}
