package model.runes;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Rune.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//

public class Rune {

	public void modifyProjectile(Projectile p) {

	}

	public void modifySlime(Slime s) {

	}

	public int getDistance() {
		return 0;
	}
}
