package model.runes;

import control.SkeletonUI;
import model.enemies.Dwarf;
import model.enemies.Elf;
import model.enemies.Hobbit;
import model.enemies.Man;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Slime.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//

public class Slime {
	public int slowMe(Dwarf d) {
		SkeletonUI.enterFunction(this, "slowMe");

		SkeletonUI.leaveFunction(0);
		return 0;
	}

	public int slowMe(Hobbit h) {
		SkeletonUI.enterFunction(this, "slowMe");

		SkeletonUI.leaveFunction(0);
		return 0;
	}

	public int slowMe(Elf e) {
		SkeletonUI.enterFunction(this, "slowMe");

		SkeletonUI.leaveFunction(0);
		return 0;
	}

	public void setNumbers(Rune r) {
		SkeletonUI.enterFunction(this, "setNumbers");

		SkeletonUI.leaveFunction();
	}

	public int slowMe(Man m) {
		SkeletonUI.enterFunction(this, "slowMe");

		SkeletonUI.leaveFunction(0);
		return 0;
	}
}
