//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ActiveUnit.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//

package model;

public interface ActiveUnit {
	public void tick();
}
