//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Dwarf.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//
package model;



public class Dwarf extends EnemyUnit {
	public void dealDamage(Projectile p) {
	
	}
	
	public void gotSlowed(Slime s) {
	
	}
}
