//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ElfRune.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//




public class ElfRune extends Rune, Rune {
	public void modifyProjectile(Projectile p) {
	
	}
	
	public void modifySlime(Slime s) {
	
	}
}
