//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EnemyUnit.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//




public class EnemyUnit implements ActiveUnit, ActiveUnit {
	private Road roadToNotice;
	private Game gameToNotice;
	public void dealDamage(Projectile p) {
	
	}
	
	public void gotSlowed(Slime s) {
	
	}
	
	public void setRoad() {
	
	}
}
