//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Field.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//




public class Field extends Tile {
	private Tower tower;
	private Tower tower;
	public bool checkTower() {
	
	}
	
	public void putRune(Rune r) {
	
	}
	
	public void putTower(Tower t) {
	
	}
	
	public bool checkRune() {
	
	}
}
