//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FinishedRoad.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//




public class FinishedRoad extends Road {
	public List<EnemyUnit> getFinishedUnits() {
	
	}
	
	public void deleteFinishedUnits() {
	
	}
}
