package model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Finish.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//



public class Finish extends Road {
}
