package model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FriendlyUnit.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//




public interface FriendlyUnit extends ActiveUnit {
	public boolean checkRune();
	
	public void putRune(Rune r);
	
	public void addUnit(EnemyUnit enemyUnit);
	
	public void removeUnit(EnemyUnit enemyUnit);
}
