//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FriendlyUnit.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//




public class FriendlyUnit implements ActiveUnit {
	public bool checkRune() {
	
	}
	
	public void putRune(Rune r) {
	
	}
	
	public void addUnit(EnemyUnit enemyUnit) {
	
	}
	
	public void removeUnit(EnemyUnit enemyUnit) {
	
	}
}
