//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Game.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//




public class Game {
	public void tick() {
	
	}
	
	public void notifyIfDead(EnemyUnit e) {
	
	}
}
