package model;

import java.util.ArrayList;
import java.util.List;

import model.enemies.EnemyUnit;
import model.friendly.Swamp;
import model.mapitem.Map;
import model.runes.Rune;
import control.SkeletonUI;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Game.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//

public class Game {

	private Map map;
	
	private Ticker ticker;

	public void Skeleton_MapSetter(Map m) {
		map = m;
	}

	public void tick() {
		// SkeletonUI.enterFunction(this, "tick");
		//
		// Ticker t = new Ticker();
		// SkeletonUI.addObject(t, "ticker", true);
		//
		// List<EnemyUnit> l = new ArrayList<EnemyUnit>();
		// SkeletonUI.addObject(l, "enemylist", false);
		//
		// if(SkeletonUI.stringQuestion("Hogy dugnád (Orálisan, Análisan, Vaginálisan)?",
		// "O", "a", "v").equals("V"))
		// t.remove(l);
		//
		// SkeletonUI.leaveFunction();
	}

	public void notifyIfDead(EnemyUnit e) {
		SkeletonUI.enterFunction(this, "notifyIfDead", e);

		List<EnemyUnit> units = new ArrayList<EnemyUnit>();
		units.add(e);
		ticker.remove(units);
		
		SkeletonUI.leaveFunction();
	}

	public void Skeleton_MouseOnTile_Rune() {
		boolean available = map.checkRune(0, 0);

		if (available) {

			Rune rune = new Rune();
			SkeletonUI.addObject(rune, "rune", true);

			map.putRune(0, 0, rune);
		}
	}

	public void Skeleton_MouseOnTile_Swamp() {
		boolean available = map.checkSwamp(0, 0);
		if (available) {
			Rune r = new Rune();
			SkeletonUI.addObject(r, "r", true);

			Swamp s = new Swamp();
			SkeletonUI.addObject(s, "s", true);

			map.putSwamp(0, 0, s);

		}

	}
	
	public void Skeleton_addTicker(Ticker t) {
		ticker = t;
	}
}
