package model;

import java.util.ArrayList;
import java.util.List;

import model.enemies.EnemyUnit;
import control.SkeletonUI;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Game.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//

public class Game {
	public void tick() {
//		SkeletonUI.enterFunction(this, "tick");
//		
//		Ticker t = new Ticker();
//		SkeletonUI.addObject(t, "ticker", true);
//		
//		List<EnemyUnit> l = new ArrayList<EnemyUnit>();
//		SkeletonUI.addObject(l, "enemylist", false);
//		
//		if(SkeletonUI.stringQuestion("Hogy dugnád (Orálisan, Análisan, Vaginálisan)?", "O", "a", "v").equals("V")) 
//			t.remove(l);
//		
//		SkeletonUI.leaveFunction();
	}

	public void notifyIfDead(EnemyUnit e) {
		SkeletonUI.enterFunction(this, "notifyIfDead", e);

		SkeletonUI.leaveFunction();
	}
}
