//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Hobbit.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//




public class Hobbit extends EnemyUnit, EnemyUnit, EnemyUnit, EnemyUnit {
	public void dealDamage(Projectile p) {
	
	}
	
	public void gotSlowed(Slime s) {
	
	}
}
