package model;

import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Map.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//

public class Map {
	public boolean checkTower(int x, int y) {
		return false;

	}

	public void putTower(int x, int y, Tower t) {

	}

	public boolean checkRune(int x, int y) {
		return false;

	}

	public void putRune(int x, int y, Rune r) {

	}

	public boolean checkSwamp(int x, int y) {
		return false;

	}

	public void putSwamp(int x, int y, Swamp s) {

	}

	public void setConnections() {

	}

	public List<EnemyUnit> getFinishedUnits() {
		return null;

	}

	public void deleteFinishedUnits() {

	}

	public void addUnit(EnemyUnit e) {

	}
}
