//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Map.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//




public class Map {
	public bool checkTower(int x, int y) {
	
	}
	
	public void putTower(int x, int y, Object t: Tower) {
	
	}
	
	public bool checkRune(Object x: int, Object y: int) {
	
	}
	
	public void putRune(int x, int y, Object r: Rune) {
	
	}
	
	public bool checkSwamp(Object x:int, Object y:int) {
	
	}
	
	public void putSwamp(Object x: int, Object y: int, Object s: Swamp) {
	
	}
	
	public void setConnections() {
	
	}
	
	public List<EnemyUnit> getFinishedUnits() {
	
	}
	
	public void deleteFinishedUnits() {
	
	}
	
	public void addUnit(EnemyUnit e) {
	
	}
}
