//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RangeRune.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//




public class RangeRune extends Rune, Rune {
	public void modifyProjectile(Projectile p) {
	
	}
}
