//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Road.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//




public class Road extends Tile {
	private EnemyUnit enemyList;
	private Swamp swamp;
	private Tower towersToNotify;
	private EnemyUnit enemyList;
	private Tower towersToNotify;
	private Swamp swamp;
	private Road nextRoad;
	public bool checkSwamp() {
	
	}
	
	public void addTower(int distance, Tower t) {
	
	}
	
	public void putRune(Rune r) {
	
	}
	
	public void deadNotice() {
	
	}
	
	public bool checkRune() {
	
	}
	
	public void putSwamp(Swamp s) {
	
	}
	
	public bool addUnit(EnemyUnit e) {
	
	}
	
	public void stepMe(EnemyUnit enemyUnit) {
	
	}
}
