//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Slime.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//




public class Slime {
	public void slowMe(Dwarf d) {
	
	}
	
	public void slowMe(Hobbit h) {
	
	}
	
	public void slowMe(Elf e) {
	
	}
	
	public void setNumbers() {
	
	}
	
	public void slowMe(Man m) {
	
	}
}
