//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Swamp.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//




public class Swamp implements ActiveUnit, FriendlyUnit {
	private EnemyUnit enemyUnits;
}
