//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ticker.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//




public class Ticker {
	private ActiveUnit unitList;
	public void tick() {
	
	}
	
	public void remove(List<EnemyUnit> unitList) {
	
	}
}
