package model;

import java.util.List;

import control.SkeletonUI;

import model.enemies.EnemyUnit;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ticker.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//

public class Ticker {

	private ActiveUnit unitList;

	public void tick() {
		SkeletonUI.enterFunction(this, "tick");
		
        SkeletonUI.leaveFunction();
	}

	public void remove(List<EnemyUnit> unitList) {
		SkeletonUI.enterFunction(this, "remove", unitList);

		SkeletonUI.leaveFunction();
	}
}
