package model;

import java.util.ArrayList;
import java.util.List;

import model.enemies.EnemyUnit;
import control.SkeletonUI;
import model.friendly.Tower;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ticker.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//

public class Ticker {

	private List<ActiveUnit> unitList = new ArrayList<ActiveUnit>();

	public void tick() {
		SkeletonUI.enterFunction(this, "tick");			
		
		unitList.get(0).tick();
		
        SkeletonUI.leaveFunction();
	}

	public void remove(List<EnemyUnit> unitList) {
		SkeletonUI.enterFunction(this, "remove", unitList);

		SkeletonUI.leaveFunction();
	}
	
	
}
