//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Tile.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//




public class Tile {
	public bool checkTower() {
	
	}
	
	public void putTower(Object t: Tower) {
	
	}
	
	public bool checkRune() {
	
	}
	
	public void putRune(Rune r) {
	
	}
	
	public bool checkSwamp() {
	
	}
	
	public void putSwamp(Object s:Swamp) {
	
	}
	
	public void addTower(Object distance: int, Object t: Tower) {
	
	}
	
	public void addNeighbours(List<Tile> neighbourList) {
	
	}
	
	public void setSucceedingRoads(List<Tile> nextRoads) {
	
	}
}
