package view;
import java.awt.Graphics;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FinishedRoadView.java
//  @ Date : 2014.05.07.
//  @ Author : 
//
//




public class FinishedRoadView extends ViewBase implements View {
	public void notifyView() {
	
	}
	
	public void draw(Graphics g) {
	
	}
}
