package view;
import java.awt.Graphics;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RangeRuneView.java
//  @ Date : 2014.05.07.
//  @ Author : 
//
//




public class RangeRuneView extends ViewBase {
	public void draw(Graphics g) {
	
	}
}
