
package view;
import java.awt.Graphics;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ViewBase.java
//  @ Date : 2014.05.07.
//  @ Author : 
//
//

public class ViewBase {
	private int x;
	private int y;
	public void draw(Graphics g) {
	
	}
}
