package view;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : View.java
//  @ Date : 2014.05.07.
//  @ Author : 
//
//



public interface View {
	public void notifyView();
}
