package model.mapitem;

import java.util.List;

import model.enemies.EnemyUnit;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FinishedRoad.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//

public class FinishedRoad extends Road {
	public List<EnemyUnit> getFinishedUnits() {
		return null;

	}

	public void deleteFinishedUnits() {

	}
}
