package model.mapitem;

import java.util.List;

import control.SkeletonUI;

import model.enemies.EnemyUnit;
import model.friendly.Swamp;
import model.friendly.Tower;
import model.runes.Rune;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Map.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//

public class Map {
	public boolean checkTower(int x, int y) {
		return false;

	}

	public void putTower(int x, int y, Tower t) {

	}

	public boolean checkRune(int x, int y) {
		SkeletonUI.enterFunction(this, "checkRune", x, y);

		SkeletonUI.leaveFunction(false);
		return false;

	}

	public void putRune(int x, int y, Rune r) {
		SkeletonUI.enterFunction(this, "putRune", x, y, r);

		SkeletonUI.leaveFunction();
	}

	public boolean checkSwamp(int x, int y) {
		return false;

	}

	public void putSwamp(int x, int y, Swamp s) {

	}

	public void setConnections() {

	}

	public List<EnemyUnit> getFinishedUnits() {
		return null;

	}

	public void deleteFinishedUnits() {

	}

	public void addUnit(EnemyUnit e) {

	}
}
