package model.mapitem;

import java.util.ArrayList;
import java.util.List;

import model.enemies.EnemyUnit;
import model.friendly.Swamp;
import model.friendly.Tower;
import model.runes.Rune;
import control.SkeletonUI;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Road.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//

public class Road extends Tile {

	private EnemyUnit enemyList;

	private Swamp swamp;

	private List<Tower> towersToNotify = new ArrayList<Tower>();

	private Road nextRoad;
	
	public void Skeleton_SwampSetter(Swamp s) {
		swamp = s;
	}

	public boolean checkSwamp() {
		SkeletonUI.enterFunction(this, "checkSwamp");
		
		SkeletonUI.leaveFunction(true);
		return true;
	}

	public void addTower(int distance, Tower t) {

	}

	public void putRune(Rune r) {
		SkeletonUI.enterFunction(this, "putRune", r);

		swamp.putRune(r);
		
		SkeletonUI.leaveFunction();
	}

	public void deadNotice(EnemyUnit e) {
		SkeletonUI.enterFunction(this, "deadNotice");

		for (Tower t : towersToNotify)
			t.removeUnit(e);
		
		if (swamp != null)
			swamp.removeUnit(e);
		
		SkeletonUI.leaveFunction();
	}

	public boolean checkRune() {
		SkeletonUI.enterFunction(this, "checkRune");

		boolean available = swamp.checkRune();

		SkeletonUI.leaveFunction(available);
		return available;
	}

	public void putSwamp(Swamp s) {
		SkeletonUI.enterFunction(this, "putSwamp", s);
           
		SkeletonUI.leaveFunction();
	}

	public boolean addUnit(EnemyUnit e) {
		return false;
	}

	public void stepMe(EnemyUnit enemyUnit) {

	}
}
