package model.mapitem;

import java.util.List;

import model.friendly.Swamp;
import model.friendly.Tower;
import model.runes.Rune;
import control.SkeletonUI;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Tile.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//

public class Tile {
	public boolean checkTower() {
		SkeletonUI.enterFunction(this, "checkTower");

		SkeletonUI.leaveFunction(false);
		return false;
	}

	public void putTower(Tower t) {
		return;
	}

	public boolean checkRune() {
		return false;
	}

	public void putRune(Rune r) {

	}

	public boolean checkSwamp() {
		SkeletonUI.enterFunction(this, "checkSwamp");

		SkeletonUI.leaveFunction(false);
		return false;
	}

	public void putSwamp(Swamp s) {

	}

	public void addTower(int distance, Tower t) {
		SkeletonUI.enterFunction(this, "addTower", distance, t);

		SkeletonUI.leaveFunction();
	}

	public void addNeighbours(List<Tile> neighbourList) {

	}

	public void setSucceedingRoads(List<Tile> nextRoads) {

	}
}
