//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Dwarf.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//
package model.enemies;

import control.SkeletonUI;
import model.runes.Projectile;
import model.runes.Slime;

public class Dwarf extends EnemyUnit {
//	public void gotHit(Projectile p) {
//
//	}
//
//	public void gotSlowed(Slime s) {
//
//	}
}
