package model.enemies;

import control.SkeletonUI;
import model.ActiveUnit;
import model.Game;
import model.mapitem.Road;
import model.runes.Projectile;
import model.runes.Slime;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EnemyUnit.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//

public class EnemyUnit implements ActiveUnit {
	private Road roadToNotice;
	private Game gameToNotice;

	public void gotHit(Projectile p) {
		SkeletonUI.enterFunction(this, "gotHit", p);

		SkeletonUI.leaveFunction();
	}

	public void gotSlowed(Slime s) {

	}

	public void setRoad() {

	}

	public void tick() {

	}
}
