package model.enemies;

import model.Game;
import model.mapitem.Road;
import model.runes.Projectile;
import model.runes.Slime;
import control.SkeletonUI;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Hobbit.java
//  @ Date : 2014.03.19.
//  @ Author : 
//
//

public class Hobbit extends EnemyUnit {

	public Hobbit(Road r, Game g) {
		roadToNotice = r;
		gameToNotice = g;
	}

	public Hobbit(Game g) {
		gameToNotice = g;
	}

	public Hobbit() {
	}

	public void gotHit(Projectile p) {
		health -= p.damageMe(this);
		
		if (health <= 0) {
			roadToNotice.deadNotice(this);
			gameToNotice.notifyIfDead(this);
		}
	}

	public void gotSlowed(Slime s) {
		SkeletonUI.enterFunction(this, "gotSlowed", s);

		SkeletonUI.leaveFunction();
	}
}